# Generated by Django 5.1.2 on 2024-11-16 21:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='company_profiles/', verbose_name='Profile Image')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'permissions': [('can_view_company', 'Can view companies'), ('can_add_company', 'Can add company'), ('can_change_company', 'Can change company'), ('can_delete_company', 'Can delete company')],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_generate_invite', 'Can generate invitation link'), ('can_view_accounts', 'Can view accounts'), ('can_add_account', 'Can add account'), ('can_change_account', 'Can change account'), ('can_delete_account', 'Can delete account')], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'permissions': [('can_view_invitation', 'Can view invitations'), ('can_add_invitation', 'Can add invitation'), ('can_change_invitation', 'Can change invitation'), ('can_delete_invitation', 'Can delete invitation')], 'verbose_name': 'Invitation', 'verbose_name_plural': 'Invitations'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'permissions': [('create_relationshiptype', 'Can create relationship type'), ('edit_relationshiptype', 'Can edit relationship type'), ('can_view_relationshiptype', 'Can view relationship types'), ('can_delete_relationshiptype', 'Can delete relationship type')], 'verbose_name': 'Relationship Type', 'verbose_name_plural': 'Relationship Types'},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='contact_profiles/', verbose_name='Profile Image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'permissions': [('can_view_contact', 'Can view contacts'), ('can_add_contact', 'Can add contact'), ('can_change_contact', 'Can change contact'), ('can_delete_contact', 'Can delete contact')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('profile_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Profile Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Company',
                'verbose_name_plural': 'historical Companies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('profile_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Profile Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.company', verbose_name='Company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contact',
                'verbose_name_plural': 'historical Contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
