# Generated by Django 5.1.2 on 2024-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='history_user',
        ),
        migrations.AddField(
            model_name='historicalinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='HistoricalContact',
        ),
    ]
