# Generated by Django 5.1.2 on 2024-10-26 22:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_building_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(db_index=True, help_text='Número de série do equipamento', max_length=100)),
                ('item_type', models.CharField(choices=[('SIMPLE', 'Simple Item'), ('SUPPLY', 'Supply')], max_length=10)),
                ('supplier', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturing_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('reception_date', models.DateField(blank=True, editable=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('L', 'Liters'), ('G', 'Grams')], max_length=2, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário responsável pelo equipamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, db_constraint=False, help_text='Sala onde o equipamento está localizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.room')),
            ],
            options={
                'verbose_name': 'historical inventory item',
                'verbose_name_plural': 'historical inventory items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(help_text='Número de série do equipamento', max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('SIMPLE', 'Simple Item'), ('SUPPLY', 'Supply')], max_length=10)),
                ('supplier', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturing_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('reception_date', models.DateField(auto_now_add=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('L', 'Liters'), ('G', 'Grams')], max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, help_text='Usuário responsável pelo equipamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Sala onde o equipamento está localizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='locations.room')),
            ],
            options={
                'permissions': [('can_view_inventoryitem', 'Pode visualizar itens de inventário'), ('can_add_inventoryitem', 'Pode adicionar itens de inventário'), ('can_change_inventoryitem', 'Pode alterar itens de inventário'), ('can_delete_inventoryitem', 'Pode deletar itens de inventário')],
            },
        ),
    ]
