# Generated by Django 5.1.2 on 2024-10-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_historicalinventoryitem_item_type_and_more'),
        ('locations', '0002_alter_building_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'permissions': [('can_view_inventoryitem', 'Can view inventory items'), ('can_add_inventoryitem', 'Can add inventory items'), ('can_change_inventoryitem', 'Can change inventory items'), ('can_delete_inventoryitem', 'Can delete inventory items')]},
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='item_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple Item'), ('SUPPLY', 'Supply'), ('TOOL', 'Tool'), ('MEASURING', 'Measuring Equipment'), ('ELECTRONIC', 'Electronic Equipment'), ('MACHINE', 'Machine'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used only for supplies', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='responsible_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User responsible for the equipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Room where the equipment is located', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.room'),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='Equipment serial number', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liters'), ('G', 'Grams'), ('U', 'Unit')], help_text='Used only for supplies', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple Item'), ('SUPPLY', 'Supply'), ('TOOL', 'Tool'), ('MEASURING', 'Measuring Equipment'), ('ELECTRONIC', 'Electronic Equipment'), ('MACHINE', 'Machine'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used only for supplies', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='User responsible for the equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room where the equipment is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='locations.room'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='Equipment serial number', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('L', 'Liters'), ('G', 'Grams'), ('U', 'Unit')], help_text='Used only for supplies', max_length=2, null=True),
        ),
    ]
