# Generated by Django 5.1.2 on 2024-11-02 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Technician responsible for calibration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcalibration',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Technician responsible for calibration', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmaintenance',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Technician responsible for maintenance', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltraining',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Technician who received the training', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Technician responsible for maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='contact',
            field=models.ForeignKey(help_text='Technician who received the training', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
