# Generated by Django 5.1.2 on 2024-10-26 22:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0002_alter_historicalinventoryitem_item_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMethodology',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da Metodologia', max_length=255)),
                ('description', models.TextField(help_text='Descrição detalhada da metodologia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou a metodologia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customuser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical methodology',
                'verbose_name_plural': 'historical methodologys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da Metodologia', max_length=255)),
                ('description', models.TextField(help_text='Descrição detalhada da metodologia')),
                ('author', models.ForeignKey(blank=True, help_text='Usuário que criou a metodologia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methodologies', to='accounts.customuser')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Lista de equipamentos utilizados na metodologia', related_name='methodology_equipment', to='inventory.inventoryitem')),
            ],
            options={
                'permissions': [('can_view_methodology', 'Pode visualizar metodologias'), ('can_add_methodology', 'Pode adicionar metodologias'), ('can_change_methodology', 'Pode alterar metodologias'), ('can_delete_methodology', 'Pode deletar metodologias')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMethodologySupply',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade do insumo utilizado', max_digits=10)),
                ('unit', models.CharField(default='Unidade', help_text='Unidade de medida, ex: litros, gramas', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(blank=True, db_constraint=False, help_text='Insumo utilizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem')),
                ('methodology', models.ForeignKey(blank=True, db_constraint=False, help_text='Metodologia à qual o insumo pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='methodology.methodology')),
            ],
            options={
                'verbose_name': 'historical methodology supply',
                'verbose_name_plural': 'historical methodology supplys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MethodologySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade do insumo utilizado', max_digits=10)),
                ('unit', models.CharField(default='Unidade', help_text='Unidade de medida, ex: litros, gramas', max_length=10)),
                ('methodology', models.ForeignKey(help_text='Metodologia à qual o insumo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='methodology.methodology')),
                ('supply', models.ForeignKey(help_text='Insumo utilizado', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_methodologies', to='inventory.inventoryitem')),
            ],
            options={
                'permissions': [('can_view_methodology_supply', 'Pode visualizar insumos de metodologias')],
                'unique_together': {('methodology', 'supply')},
            },
        ),
    ]
