# Generated by Django 5.1.2 on 2024-11-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_options_and_more'),
        ('methodology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodology',
            options={'permissions': [('can_view_methodology', 'Can view methodologies'), ('can_add_methodology', 'Can add methodologies'), ('can_change_methodology', 'Can change methodologies'), ('can_delete_methodology', 'Can delete methodologies')]},
        ),
        migrations.AlterModelOptions(
            name='methodologysupply',
            options={'permissions': [('can_view_methodology_supply', 'Can view methodology supplies')]},
        ),
        migrations.AlterField(
            model_name='historicalmethodology',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created the methodology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmethodology',
            name='description',
            field=models.TextField(help_text='Detailed description of the methodology'),
        ),
        migrations.AlterField(
            model_name='historicalmethodology',
            name='title',
            field=models.CharField(help_text='Title of the Methodology', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalmethodologysupply',
            name='methodology',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Methodology to which the supply belongs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='methodology.methodology'),
        ),
        migrations.AlterField(
            model_name='historicalmethodologysupply',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of the supply used', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalmethodologysupply',
            name='supply',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supply used', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='historicalmethodologysupply',
            name='unit',
            field=models.CharField(default='Unit', help_text='Unit of measurement, e.g., liters, grams', max_length=10),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User who created the methodology', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methodologies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='description',
            field=models.TextField(help_text='Detailed description of the methodology'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='List of equipment used in the methodology', related_name='methodology_equipment', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='title',
            field=models.CharField(help_text='Title of the Methodology', max_length=255),
        ),
        migrations.AlterField(
            model_name='methodologysupply',
            name='methodology',
            field=models.ForeignKey(help_text='Methodology to which the supply belongs', on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='methodology.methodology'),
        ),
        migrations.AlterField(
            model_name='methodologysupply',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of the supply used', max_digits=10),
        ),
        migrations.AlterField(
            model_name='methodologysupply',
            name='supply',
            field=models.ForeignKey(help_text='Supply used', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_methodologies', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='methodologysupply',
            name='unit',
            field=models.CharField(default='Unit', help_text='Unit of measurement, e.g., liters, grams', max_length=10),
        ),
    ]
