# Generated by Django 5.1.2 on 2024-10-14 14:41

import django.db.models.deletion
import locations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'permissions': [('can_view_building', 'Pode visualizar edifícios'), ('can_add_building', 'Pode adicionar edifícios'), ('can_change_building', 'Pode alterar edifícios'), ('can_delete_building', 'Pode deletar edifícios')], 'verbose_name': 'Edifício', 'verbose_name_plural': 'Edifícios'},
        ),
        migrations.AlterModelOptions(
            name='historicalbuilding',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Edifício', 'verbose_name_plural': 'historical Edifícios'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeasurement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Medição', 'verbose_name_plural': 'historical Medições'},
        ),
        migrations.AlterModelOptions(
            name='historicalroom',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sala', 'verbose_name_plural': 'historical Salas'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'permissions': [('can_view_measurement', 'Pode visualizar medições'), ('can_add_measurement', 'Pode adicionar medições'), ('can_change_measurement', 'Pode alterar medições'), ('can_delete_measurement', 'Pode deletar medições')], 'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('can_view_room', 'Pode visualizar salas'), ('can_add_room', 'Pode adicionar salas'), ('can_change_room', 'Pode alterar salas'), ('can_delete_room', 'Pode deletar salas')], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do edifício', null=True, upload_to=locations.models.building_image_upload_path),
        ),
        migrations.AlterField(
            model_name='building',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pelo edifício', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbuilding',
            name='image',
            field=models.TextField(blank=True, help_text='Imagem do edifício', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbuilding',
            name='responsible_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário responsável pelo edifício', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmeasurement',
            name='humidity',
            field=models.FloatField(help_text='Percentual de umidade'),
        ),
        migrations.AlterField(
            model_name='historicalmeasurement',
            name='recorded_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Data e hora da medição'),
        ),
        migrations.AlterField(
            model_name='historicalmeasurement',
            name='temperature',
            field=models.FloatField(help_text='Temperatura em Celsius'),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='capacity',
            field=models.IntegerField(help_text='Capacidade máxima da sala'),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='floor',
            field=models.CharField(help_text='Número ou identificador do andar', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='image',
            field=models.TextField(blank=True, help_text='Imagem da sala', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='responsible_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário responsável pela sala', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='humidity',
            field=models.FloatField(help_text='Percentual de umidade'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da medição'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(help_text='Temperatura em Celsius'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(help_text='Capacidade máxima da sala'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(help_text='Número ou identificador do andar', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem da sala', null=True, upload_to=locations.models.room_image_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela sala', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
